apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: riag-tech-team-ap-maximus-app

resources:
  - ../../base/angular-fe

patchesStrategicMerge:
  - deployment-changes.yaml
  - virtualservice-changes.yaml

configMapGenerator:
  - name: angular-fe-env-vars
    literals:
      - ENVIRONMENT=staging

images:
  - name: riag.jfrog.io/docker-virtual/application-platform/staging/riag/tech/platforms/team-ap/maximus-app/angular-fe
    digest: <TO-BE-REPLACED-BY-FIRST-BUILD>