apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: riag-tech-team-ap-maximus-app
resources:
- ../../base/spring-be
- vault-injector-config.yaml
patchesStrategicMerge:
- deployment-changes.yaml
- virtualservice-changes.yaml
configMapGenerator:
- name: spring-be-env-vars
  literals:
  - ENVIRONMENT=staging
  - SPRING_PROFILES_ACTIVE=staging
  - GOOGLE_PROJECT_ID=rd-platform-k8s-staging
  - GOOGLE_CLOUD_PROJECT=rd-platform-k8s-staging
  - CLUSTER_NAME=staging
  - CONTAINER_NAME=spring-be
  - LOCATION=europe-west4-a
images:
- name: riag.jfrog.io/docker-virtual/application-platform/staging/riag/tech/platforms/team-ap/maximus-app/spring-be
  digest: <TO-BE-REPLACED-BY-FIRST-BUILD>
